version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
    
  backend:
    image: node:alpine
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db

  frontend:
    build: ./frontend
    ports:
    - "80:80"
    depends_on:
      - backend
volumes:
  db-data: 